//<<<<<<< HEAD
//﻿using System;
//using System.Collections.Generic;
//=======
//﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//namespace Entities;

//public partial class Order
//{
//<<<<<<< HEAD
//=======
//    [Key]
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//    public int OrderId { get; set; }

//    public int UserId { get; set; }

//    public DateOnly OrderDate { get; set; }

//    public int Status { get; set; }

//    public double TotalPrice { get; set; }

//<<<<<<< HEAD
//    public string ShippingMethod { get; set; } = null!;

//    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

//    public virtual User User { get; set; } = null!;
//}
//=======
//    [Required]
//    [StringLength(60)]
//    public string ShippingMethod { get; set; }

//    [InverseProperty("Order")]
//    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

//    [ForeignKey("UserId")]
//    [InverseProperty("Orders")]
//    public virtual User User { get; set; }
//}
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities;

public partial class Order
{
    [Key]
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public DateOnly OrderDate { get; set; }

    public int Status { get; set; }

    public double TotalPrice { get; set; }

    [Required]
    [StringLength(60)]
    public string ShippingMethod { get; set; } = null!;

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; } = null!;
}