//<<<<<<< HEAD
//﻿using System;
//using System.Collections.Generic;
//=======
//﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//namespace Entities;

//public partial class OrderItem
//{
//<<<<<<< HEAD
//=======
//    [Key]
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//    public int OrderItemId { get; set; }

//    public int OrderId { get; set; }

//    public int ProductId { get; set; }

//    public int Quantity { get; set; }

//    public double Size { get; set; }

//    public double PriceAtPurchase { get; set; }

//<<<<<<< HEAD
//    public virtual Order Order { get; set; } = null!;

//    public virtual Product Product { get; set; } = null!;
//}
//=======
//    [ForeignKey("OrderId")]
//    [InverseProperty("OrderItems")]
//    public virtual Order Order { get; set; }

//    [ForeignKey("ProductId")]
//    [InverseProperty("OrderItems")]
//    public virtual Product Product { get; set; }
//}
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities;

public partial class OrderItem
{
    [Key]
    public int OrderItemId { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public double Size { get; set; }

    public double PriceAtPurchase { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; } = null!;

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItems")]
    public virtual Product Product { get; set; } = null!;
}