//<<<<<<< HEAD
//﻿using System;
//using System.Collections.Generic;
//=======
//﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using Microsoft.EntityFrameworkCore;
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//namespace Entities;

//public partial class Product
//{
//<<<<<<< HEAD
//    public int ProductId { get; set; }

//    public string ProductName { get; set; } = null!;

//    public string ShortDescription { get; set; } = null!;

//    public string LongDescription { get; set; } = null!;
//=======
//    [Key]
//    public int ProductId { get; set; }

//    [Required]
//    [StringLength(40)]
//    public string ProductName { get; set; }

//    [Required]
//    [StringLength(100)]
//    public string ShortDescription { get; set; }

//    [Required]
//    public string LongDescription { get; set; }
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//    public double ProductPrice { get; set; }

//    public int CategoryId { get; set; }

//<<<<<<< HEAD
//    public string Color { get; set; } = null!;

//    public DateOnly DateAdded { get; set; }

//    public string Image1 { get; set; } = null!;

//    public string? Image2 { get; set; }
//=======
//    [Required]
//    [StringLength(30)]
//    public string Color { get; set; }

//    public DateOnly DateAdded { get; set; }

//    [Required]
//    [StringLength(100)]
//    public string Image1 { get; set; }

//    [Required]
//    [StringLength(100)]
//    public string Image2 { get; set; }
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//    public bool JustOnline { get; set; }

//    public bool IsClassic { get; set; }

//    public bool IsTrendy { get; set; }

//    public bool IsPearls { get; set; }

//    public bool IsStudio { get; set; }

//<<<<<<< HEAD
//    public virtual Category Category { get; set; } = null!;

//    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

//    public virtual ICollection<Size> Sizes { get; set; } = new List<Size>();
//}
//=======
//    [ForeignKey("CategoryId")]
//    [InverseProperty("Products")]
//    public virtual Category Category { get; set; }

//    [InverseProperty("Product")]
//    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
//    //[InverseProperty("Product")]
//    public virtual ICollection<WebApiShop.Entities.Size> Sizes { get; set; } = new List<WebApiShop.Entities.Size>();
//}
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    public int ProductId { get; set; }

    [Required]
    [StringLength(40)]
    public string ProductName { get; set; } = null!;

    [Required]
    [StringLength(100)]
    public string ShortDescription { get; set; } = null!;

    [Required]
    public string LongDescription { get; set; } = null!;

    public double ProductPrice { get; set; }

    public int CategoryId { get; set; }

    [Required]
    [StringLength(30)]
    public string Color { get; set; } = null!;

    public DateOnly DateAdded { get; set; }

    [Required]
    [StringLength(100)]
    public string Image1 { get; set; } = null!;

    [StringLength(100)]
    public string? Image2 { get; set; }

    public bool JustOnline { get; set; }

    public bool IsClassic { get; set; }

    public bool IsTrendy { get; set; }

    public bool IsPearls { get; set; }

    public bool IsStudio { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; } = null!;

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Size> Sizes { get; set; } = new List<Size>();
}