//<<<<<<< HEAD
//﻿using System;
//using System.Collections.Generic;

//namespace Entities;

//public partial class Size
//{
//    public int SizeId { get; set; }

//    public int ProductId { get; set; }

//    public double ProductSize { get; set; }

//    public int Amount { get; set; }

//    public virtual Product Product { get; set; } = null!;
//}
//=======
//﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using Entities;
//using Microsoft.EntityFrameworkCore;

//namespace WebApiShop.Entities;

//public class Size
//{
//    public int SizeId { get; set; }        // תואם ל-PK ב-SQL
//    public int ProductId { get; set; }     // תואם ל-FK ב-SQL
//    public string ProductSize { get; set; }
//    public int Amount { get; set; }

//    // קשר ניווט חזרה למוצר (אופציונלי אך מומלץ)
//    public virtual Product Product { get; set; }
//}
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    public partial class Size
    {
        [Key]
        public int SizeId { get; set; }

        public int ProductId { get; set; }

        // הערה: ודאי אם ב-DB זה מוגדר כמספר או טקסט. השארתי string לפי הגרסה המעודכנת
        [Required]
        public string ProductSize { get; set; } = null!;

        public int Amount { get; set; }

        [ForeignKey("ProductId")]
        public virtual Product Product { get; set; } = null!;
    }
}