// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Entities;
using Microsoft.EntityFrameworkCore;

namespace WebApiShop.Entities;

public class Size
{
    public int SizeId { get; set; }        // תואם ל-PK ב-SQL
    public int ProductId { get; set; }     // תואם ל-FK ב-SQL
    public string ProductSize { get; set; }
    public int Amount { get; set; }

    // קשר ניווט חזרה למוצר (אופציונלי אך מומלץ)
    public virtual Product Product { get; set; }
}