// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Entities;
using Microsoft.EntityFrameworkCore;

namespace WebApiShop.Entities;

[Keyless]
public partial class Size
{
    public int ProductId { get; set; }

    public double ProductSize { get; set; }

    public int Amount { get; set; }

    [ForeignKey("ProductId")]
    public virtual Product Product { get; set; }
}