//<<<<<<< HEAD
//﻿using System;
//using System.Collections.Generic;
//=======
//﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//namespace Entities;

//public partial class User
//{
//<<<<<<< HEAD
//    public int UserId { get; set; }

//    public string Email { get; set; } = null!;

//    public string? FirstName { get; set; }

//    public string? LastName { get; set; }

//    public string Password { get; set; } = null!;

//    public int Phone { get; set; }

//    public string City { get; set; } = null!;

//    public string Street { get; set; } = null!;
//=======
//    [Key]
//    public int UserId { get; set; }

//    [Required]
//    [StringLength(30)]
//    public string Email { get; set; }

//    [StringLength(20)]
//    public string FirstName { get; set; }

//    [StringLength(20)]
//    public string LastName { get; set; }

//    [Required]
//    [StringLength(20)]
//    public string Password { get; set; }

//    public int Phone { get; set; }

//    [Required]
//    [StringLength(20)]
//    public string City { get; set; }

//    [Required]
//    [StringLength(30)]
//    public string Street { get; set; }
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//    public int HouseNumber { get; set; }

//    public bool IsAdmin { get; set; }

//<<<<<<< HEAD
//    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
//}
//=======
//    [InverseProperty("User")]
//    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
//}
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities;

public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(30)]
    public string Email { get; set; } = null!;

    [StringLength(20)]
    public string? FirstName { get; set; }

    [StringLength(20)]
    public string? LastName { get; set; }

    [Required]
    [StringLength(20)]
    public string Password { get; set; } = null!;

    public int Phone { get; set; }

    [Required]
    [StringLength(20)]
    public string City { get; set; } = null!;

    [Required]
    [StringLength(30)]
    public string Street { get; set; } = null!;

    public int HouseNumber { get; set; }

    public bool IsAdmin { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}