// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Entities;
using Microsoft.EntityFrameworkCore;

namespace Repository;

public partial class JewelryStoreContext : DbContext
{
    public JewelryStoreContext(DbContextOptions<JewelryStoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.Property(e => e.CategoryName).IsFixedLength();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.Property(e => e.ShippingMethod).IsFixedLength();

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_User");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItem_Order");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItem_Product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.Property(e => e.Color).IsFixedLength();
            entity.Property(e => e.Image1).IsFixedLength();
            entity.Property(e => e.Image2).IsFixedLength();
            entity.Property(e => e.IsClassic).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsClassic");
            entity.Property(e => e.IsPearls).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsPearls");
            entity.Property(e => e.IsStudio).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsStudio");
            entity.Property(e => e.IsTrendy).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsTrendy");
            entity.Property(e => e.JustOnline).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_JustOnline");
            entity.Property(e => e.ProductName).IsFixedLength();
            entity.Property(e => e.ShortDescription).IsFixedLength();

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Category");
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.HasOne(d => d.Product).WithMany()
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Size_Product");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.City).IsFixedLength();
            entity.Property(e => e.Email).IsFixedLength();
            entity.Property(e => e.FirstName).IsFixedLength();
            entity.Property(e => e.IsAdmin).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsAdmin");
            entity.Property(e => e.LastName).IsFixedLength();
            entity.Property(e => e.Password).IsFixedLength();
            entity.Property(e => e.Street).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}