//<<<<<<< HEAD
//﻿using System;
//using System.Collections.Generic;
//using Entities;
//using Microsoft.EntityFrameworkCore;
//=======
//﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using Entities;
//using Microsoft.EntityFrameworkCore;
//using WebApiShop.Entities;
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca

//namespace Repository;

//public partial class JewelryStoreContext : DbContext
//{
//<<<<<<< HEAD
//    public JewelryStoreContext()
//    {
//    }

//=======
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//    public JewelryStoreContext(DbContextOptions<JewelryStoreContext> options)
//        : base(options)
//    {
//    }

//    public virtual DbSet<Category> Categories { get; set; }

//    public virtual DbSet<Order> Orders { get; set; }

//    public virtual DbSet<OrderItem> OrderItems { get; set; }

//    public virtual DbSet<Product> Products { get; set; }

//    public virtual DbSet<Size> Sizes { get; set; }

//    public virtual DbSet<User> Users { get; set; }

//<<<<<<< HEAD
//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=JewelryStore;Trusted_Connection=True;TrustServerCertificate=True");

//=======
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<Category>(entity =>
//        {
//<<<<<<< HEAD
//            entity.HasKey(e => e.CaregoryId);

//            entity.Property(e => e.CategoryName)
//                .HasMaxLength(40)
//                .IsFixedLength();
//=======
//            entity.Property(e => e.CategoryName).IsFixedLength();
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//        });

//        modelBuilder.Entity<Order>(entity =>
//        {
//<<<<<<< HEAD
//            entity.Property(e => e.ShippingMethod)
//                .HasMaxLength(60)
//                .IsFixedLength();

//            entity.HasOne(d => d.User).WithMany(p => p.Orders)
//                .HasForeignKey(d => d.UserId)
//=======
//            entity.Property(e => e.ShippingMethod).IsFixedLength();

//            entity.HasOne(d => d.User).WithMany(p => p.Orders)
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Order_User");
//        });

//        modelBuilder.Entity<OrderItem>(entity =>
//        {
//            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
//<<<<<<< HEAD
//                .HasForeignKey(d => d.OrderId)
//=======
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_OrderItem_Order");

//            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
//<<<<<<< HEAD
//                .HasForeignKey(d => d.ProductId)
//=======
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_OrderItem_Product");
//        });

//        modelBuilder.Entity<Product>(entity =>
//        {
//<<<<<<< HEAD
//            entity.Property(e => e.Color)
//                .HasMaxLength(30)
//                .IsFixedLength();
//            entity.Property(e => e.Image1)
//                .HasMaxLength(100)
//                .IsFixedLength();
//            entity.Property(e => e.Image2)
//                .HasMaxLength(100)
//                .IsFixedLength();
//            entity.Property(e => e.ProductName)
//                .HasMaxLength(40)
//                .IsFixedLength();
//            entity.Property(e => e.ShortDescription)
//                .HasMaxLength(100)
//                .IsFixedLength();

//            entity.HasOne(d => d.Category).WithMany(p => p.Products)
//                .HasForeignKey(d => d.CategoryId)
//=======
//            entity.Property(e => e.Color).IsFixedLength();
//            entity.Property(e => e.Image1).IsFixedLength();
//            entity.Property(e => e.Image2).IsFixedLength();
//            entity.Property(e => e.IsClassic).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsClassic");
//            entity.Property(e => e.IsPearls).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsPearls");
//            entity.Property(e => e.IsStudio).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsStudio");
//            entity.Property(e => e.IsTrendy).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsTrendy");
//            entity.Property(e => e.JustOnline).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_JustOnline");
//            entity.Property(e => e.ProductName).IsFixedLength();
//            entity.Property(e => e.ShortDescription).IsFixedLength();

//            entity.HasOne(d => d.Category).WithMany(p => p.Products)
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Product_Category");
//        });

//<<<<<<< HEAD
//        modelBuilder.Entity<Size>(entity =>
//        {
//            entity.HasOne(d => d.Product).WithMany(p => p.Sizes)
//                .HasForeignKey(d => d.ProductId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Size_Product");
//=======
//        // הגדרת טבלת Sizes
//        modelBuilder.Entity<Size>(entity =>
//        {
//            entity.HasKey(e => e.SizeId); // הגדרת מפתח ראשי

//            // הגדרת הקשר: לכל מוצר יש הרבה מידות
//            entity.HasOne(d => d.Product)
//                  .WithMany(p => p.Sizes)
//                  .HasForeignKey(d => d.ProductId)
//                  .OnDelete(DeleteBehavior.Cascade); // אם מוצר נמחק, המידות נמחקות איתו
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//        });

//        modelBuilder.Entity<User>(entity =>
//        {
//<<<<<<< HEAD
//            entity.Property(e => e.City)
//                .HasMaxLength(20)
//                .IsFixedLength();
//            entity.Property(e => e.Email)
//                .HasMaxLength(30)
//                .IsFixedLength();
//            entity.Property(e => e.FirstName)
//                .HasMaxLength(20)
//                .IsFixedLength();
//            entity.Property(e => e.LastName)
//                .HasMaxLength(20)
//                .IsFixedLength();
//            entity.Property(e => e.Password)
//                .HasMaxLength(20)
//                .IsFixedLength();
//            entity.Property(e => e.Street)
//                .HasMaxLength(20)
//                .IsFixedLength();
//=======
//            entity.Property(e => e.City).IsFixedLength();
//            entity.Property(e => e.Email).IsFixedLength();
//            entity.Property(e => e.FirstName).IsFixedLength();
//            entity.Property(e => e.IsAdmin).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsAdmin");
//            entity.Property(e => e.LastName).IsFixedLength();
//            entity.Property(e => e.Password).IsFixedLength();
//            entity.Property(e => e.Street).IsFixedLength();
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
//<<<<<<< HEAD
//}
//=======
//}
//>>>>>>> 234722a0f9ae8bbfeb6eba645db360cb10d20bca
using System;
using System.Collections.Generic;
using Entities;
using Microsoft.EntityFrameworkCore;

namespace Repository;

public partial class JewelryStoreContext : DbContext
{
    public JewelryStoreContext()
    {
    }

    public JewelryStoreContext(DbContextOptions<JewelryStoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<OrderItem> OrderItems { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<Size> Sizes { get; set; }
    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId);
            entity.Property(e => e.CategoryName).HasMaxLength(40).IsFixedLength();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.Property(e => e.ShippingMethod).HasMaxLength(60).IsFixedLength();
            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_User");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItem_Order");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItem_Product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.Property(e => e.Color).HasMaxLength(30).IsFixedLength();
            entity.Property(e => e.ProductName).HasMaxLength(40).IsFixedLength();
            // הוספת ברירות המחדל מה-Database
            entity.Property(e => e.IsClassic).HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsClassic");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Category");
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.HasKey(e => e.SizeId);
            entity.HasOne(d => d.Product).WithMany(p => p.Sizes)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Size_Product");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Email).HasMaxLength(30).IsFixedLength();
            entity.Property(e => e.Password).HasMaxLength(20).IsFixedLength();
            entity.Property(e => e.IsAdmin).HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsAdmin");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}